permalink: /:categories/:title/
url: "http://example.com"
full_name: "Pas Ramadan Dapat Hidayah"
first_name: "PasRaH"
last_name: ""
blog_title: "PasRaH"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "Gersang bumi tanpa hujan, gersang akal tanpa ilmu, gersang hati tanpa iman, gersang jiwa tanpa amal.
marhaban ya ramadhan. 
selamat menunaikan ibadah puasa mohon maaf lahir dan bathin
."
